### PR TITLE
Use workers for processing files

### PR DESCRIPTION
**Pull request by mafredri**
Sorry for the PR bombardment, I started hacking on this yesterday and wanted to put this up for discussion.

At first I only implemented a hashing worker, but I saw there was a pretty big speedup in processing multiple files simultaneously when using a fingerprint database as well.

Here we, by default, spin up `GOMAXPROCS` workers for processing files. This includes checking their mime type and computing the hash.

A RWMutex was added to `DB` to prevent concurrent reads and writes. Concurrent reads are supported by mattn/go-sqlite3 (hence the RW Mutex).

I'm open to making any changes you deem appropriate.

And thanks a lot for this program 😄!

### CODE REVIEW

**Comment by opennota** [comment]
Great! That's something I wanted to implement, but never did. I'll look at the changes.

**Comment by mafredri** [comment]
Hi @opennota, thanks for considering this PR!

I noticed a couple of issues that were due to my previous hashing worker rewrite that have been fixed now.

Some thoughts regarding this PR:

- I considered using sync Map (instead of `resultWorker`), but I wanted it to be compatible with pre-1.9 versions of Go
- The spinner now spins for the most recent file (meaning there might still be `cores-1` other files being processed)
    - I think this is OK for now, but eventually we could have one line/spinner per `core`, but this requires some more advanced terminal text manipulation
- Is `cores` a good name for the flag, or should we rename it to something else?

PS. I've seen some potentially concerning out since this change (I think it might have been overwritten by the spinner previously, but I'm not sure)

```
sh: ./convert: No such file or directory
sh: ./convert: No such file or directory
sh: gm: command not found
sh: gm: command not found
```

I'm not sure where these originate from, probably pHash, but perhaps you know more? Is it a concern?

**Comment by opennota** [comment]
> I considered using sync Map (instead of resultWorker), but I wanted it to be compatible with pre-1.9 versions of Go

+1.

> Is cores a good name for the flag, or should we rename it to something else?

I think the common name for this flag is `-j` / `--jobs`.

```
sh: ./convert: No such file or directory
sh: gm: command not found
```
These are from [CImg](https://github.com/opennota/phash/tree/master/c++/CImg), which is used by pHash. I need to make sure it is safe to call phash concurrently from multiple goroutines.

**Comment by mafredri** [comment]
> I think the common name for this flag is -j / --jobs.

I'll update the PR 👍 !

> These are from CImg, which is used by pHash. I need to make sure it is safe to call phash concurrently from multiple goroutines.

Ah you're right, looks like they're from `imagemagick_path` which seems to be guarded by a mutex, AFAICT. I'm guessing this is called the first time the library is used. Seems harmless but the initial work might be done multiple times.

**Comment by opennota** [comment]
I've updated CImg (run `go get -u github.com/opennota/phash` to update the phash package; then rebuild findimagedupes) and the warnings are gone. All in all the whole worker thing seems to be working.

I'm merging. Thanks!

**Comment by mafredri** [comment]
Awesome, thanks for the quick turn-around! Btw, I didn't see any new commits to phash yet?

**Comment by opennota** [comment]
Oh, sorry, forgot to push. Updated.

**Pull request merged**
